version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.9.7
  working_directory: ~/project

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/song-popularity-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox  
      - run:
          name: Running app tests
          command: |
            tox

  deploy_app:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: deploy to heroku
          command: |
            git subtree push --prefix song-popularity-api https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  app:
    jobs:
      - test_app
      - deploy_app:
          requires:
            - test_app
          filters:
            branches:
              only:
                - master